### ISSUE TITLE
Question about firmware

### ISSUE THREAD

**Issue by zenmetsu** [petercpark/stenokeyboards-firmware#1]
I will try to be brief.  I am attempting to use my Uni v3 (stock firmware) with my Android device.  The software that I am using claims to support the ATMEGA32U4 when using CDC protocol.  I am just checking to see if the CDC protocol is used by the stock firmware prior to seeking assistance from the developer of the USB library.

The USB library that I am trying to work with is located here: https://github.com/mik3y/usb-serial-for-android

Thanks!

**Comment by petercpark** [comment]
The Uni v3 uses the Gemini PR protocol. I have never heard of the CDC protocol. If you get the qwerty firmware and flash it on your keyboard, you can use steno on your Android device using a software called Dotterel. Here is a link to Dotterel: https://github.com/nimble0/dotterel/releases/tag/v0.3.1-dev

**Comment by zenmetsu** [comment]
OK, thanks.  I am trying to use Dotterel, but it uses the USB serial library listed above, which seems to be incompatible with the stock firmware.  

I suppose I might need to buy two keyboards since I am not at a point where I can use the QWERTY firmware fulltime on my PC.  

CDC is just USB communications device class... which provides a serial interface to things like Arduino via USB.  I was just checking if the base firmware is built such that USB CDC/ACM was used, as references to CDC do exist in the QMK firmware code

**Comment by zenmetsu** [comment]
I will close this ticket.  It appears that the issue is that the Uni presents itself with a custom vendor/product ID and the library is not supporting it.
